// import { Geist, Geist_Mono } from "next/font/google";
import "./reset.css";
import "./globals.css";

import HeaderComponent from "./components/HeaderComponent";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Apple",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderComponent />

        {children}
      </body>
    </html>
  );
}
